all: jumping

jumping: jumping.c
	gcc -lmraa -o jumping jumping.c

clean:
	rm -rf jumping *~
	rm -rf jump_low_peaksAndTroughs.csv
	rm -rf jumps_low.csv
	rm -rf jump_low_training_file.txt
	rm -rf jump_high_peaksAndTroughs.csv
	rm -rf jumps_high.csv
	rm -rf jump_high_training_file.txt
